"""Initial revision

Revision ID: 68f64a3addc0
Revises: 
Create Date: 2022-11-13 21:19:56.524424

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68f64a3addc0'
down_revision = None
branch_labels = None
depends_on = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('punishment_type',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('severity',
    sa.Column('id', sa.SmallInteger(), nullable=False),
    sa.Column('level', sa.SmallInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('level'),
    sa.UniqueConstraint('name')
    )
    op.create_table('user',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('password', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('action',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('severity_id', sa.SmallInteger(), nullable=True),
    sa.Column('content', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['severity_id'], ['severity.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('content')
    )
    op.create_table('punishment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('action_id', sa.BigInteger(), nullable=True),
    sa.Column('punishment_type_id', sa.SmallInteger(), nullable=True),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['action_id'], ['action.id'], ),
    sa.ForeignKeyConstraint(['punishment_type_id'], ['punishment_type.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('assigned_punishment',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=True),
    sa.Column('punishment_id', sa.BigInteger(), nullable=True),
    sa.Column('user_id', sa.BigInteger(), nullable=True),
    sa.ForeignKeyConstraint(['punishment_id'], ['punishment.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('assigned_punishment')
    op.drop_table('punishment')
    op.drop_table('action')
    op.drop_table('user')
    op.drop_table('severity')
    op.drop_table('punishment_type')
    # ### end Alembic commands ###
